name: "Update assets and README"

on:
  push:
    branches:
      - main

jobs:
  master:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    name: "Push to main"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: "callout-boxes"
